---
- name: Engine CS | Add Docker’s public key for CS packages
  shell: curl -s 'https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e' | sudo apt-key add --import

- name: Engine CS | Install HTTPS helper and virtual drivers
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - apt-transport-https
    - linux-image-extra-virtual

- name: Engine CS | Add repository for new version
  shell:
    echo "deb https://packages.docker.com/1.12/apt/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
    creates=/etc/apt/sources.list.d/docker.list

- name: Engine CS | Install Engine
  apt: name=docker-engine update_cache=yes
